### ISSUE TITLE
Real world robot code

### ISSUE THREAD

**Issue by zixuwang-cs** [LYX0501/DiscussNav#1]
Thanks for your excellent work. Could you provide the code for the robot in a real-world environment?

**Comment by liumingzs** [comment]
Excuse me，can you run through this code?

**Comment by zixuwang-cs** [comment]
> Excuse me，can you run through this code?

I can run the code but it costs me a bit due to the problem of loading model.
Maybe you should be careful about the model path you load, and you won't get any warning if you input the wrong model path.
https://github.com/LYX0501/DiscussNav/blob/1b0c926c25e78122f0459ef50fd87a3889b64580/DiscussNav.py#L131-L139
Good luck!

**Comment by liumingzs** [comment]
> > Excuse me，can you run through this code?
> 
> I can run the code but it costs me a bit due to the problem of loading model. Maybe you should be careful about the model path you load, and you won't get any warning if you input the wrong model path.
> 
> https://github.com/LYX0501/DiscussNav/blob/1b0c926c25e78122f0459ef50fd87a3889b64580/DiscussNav.py#L131-L139
> 
> Good luck!

Thank you for your response. I am indeed encountering this issue. Could you please advise on how to modify the model path? Could you provide a more detailed explanation? I would greatly appreciate it.
I am certain that the _ram_swin_large_14m.pth_ model is located at the path **/media/zs/T71/recognize-anything/ckpt/ram_swin_large_14m.pth.** 
**ram_path = "/media/zs/T71/recognize-anything/ckpt/ram_swin_large_14m.pth"**
How should I modify the path?

**terminator print:**
```
/media/zs/T71/Matterport3DSimulator$ python DiscussNav.py 
INFO - 2024-06-07 10:47:54,183 - DiscussNav - Attempt 1 to load models.
INFO - 2024-06-07 10:48:20,713 - blip2_t5_instruct - freeze vision encoder
Loading checkpoint shards: 100%|██████████████████| 2/2 [00:02<00:00,  1.20s/it]
INFO - 2024-06-07 10:49:49,372 - blip2 - load checkpoint from https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/InstructBLIP/instruct_blip_flanxl_trimmed.pth
/encoder/layer/0/crossattention/self/query is tied
/encoder/layer/0/crossattention/self/key is tied
/encoder/layer/0/crossattention/self/value is tied
/encoder/layer/0/crossattention/output/dense is tied
/encoder/layer/0/crossattention/output/LayerNorm is tied
/encoder/layer/0/intermediate/dense is tied
/encoder/layer/0/output/dense is tied
/encoder/layer/0/output/LayerNorm is tied
/encoder/layer/1/crossattention/self/query is tied
/encoder/layer/1/crossattention/self/key is tied
/encoder/layer/1/crossattention/self/value is tied
/encoder/layer/1/crossattention/output/dense is tied
/encoder/layer/1/crossattention/output/LayerNorm is tied
/encoder/layer/1/intermediate/dense is tied
/encoder/layer/1/output/dense is tied
/encoder/layer/1/output/LayerNorm is tied
--------------
/media/zs/T71/recognize-anything/ckpt/ram_swin_large_14m.pth
--------------
load checkpoint from /media/zs/T71/recognize-anything/ckpt/ram_swin_large_14m.pth
vit: swin_l
  0%|                                                   | 0/783 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "DiscussNav.py", line 555, in <module>
    main(dataset_name, ram_path)
  File "DiscussNav.py", line 506, in main
    sim.newEpisode([scanId], [start_vp], [start_heading], [0])
ValueError: MatterSim: Could not open skybox RGB files at: ./data/v1/scans//8194nk5LbLH/matterport_skybox_images/c9e8dc09263e4d0da77d16de0ecddd39_skybox_small.jpg

```

**Comment by zixuwang-cs** [comment]
Your problem is not about the model path, maybe you should check the dataset path.

**Comment by liumingzs** [comment]
Can I get your  **wechat** to ask the problem about how to deal with the dataset , my number is 15190680385.I'm really don't know how to unzip the dataset.Thanks a lot.

**Comment by liumingzs** [comment]
My question is how to unzip the dataset，every file  has to unzip？

**Comment by zixuwang-cs** [comment]
Sorry, I'm focusing on real-world navigation and running without the simulator.

**Comment by liumingzs** [comment]
My research focuses on enlarged models of robots, and I also focus on the real world. Do you have any good suggestions, I would like to share with you some research in this area, I am a person who has just moved into this direction
